### ISSUE TITLE
scratch image can not state running status

### ISSUE THREAD

**Issue by weironz** [Angatar/kubectl#1]
scratch maybe not a good idea ,how to make the image alway running in jenkins， not support any command.

```
pipeline {   
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: kubectl
    image: d3fk/kubectl
    command:
    - cat
    tty: true
```

**Comment by Angatar** [comment]
This kubectl image based from scratch was made to provide a  kubectl official binary in a minimalist container.

It is made to be run on each kubectl command (and not to be a pending kubectl service). 

**It can support all kubectl commands.** 

So, you can run any kubectl command(s) by using the d3fk/kubectl image from your jenkins pipeline(s) and you can create as much commands and pipelines as you need.

In case you really need to make it pending for any reason, you could imagine to run a pending command from this container in an another pod/container of your cluster e.g. if you wish to use a ```cat``` command with tty as in your example consider the following command: ```kubectl exec -ti  deployment/busybox_existing_container -- cat```
In case you don't want to use an existing container you could also run a new pending container with the kubectl  run command e.g. ```kubectl run -i -t busybox --image=busybox  --restart=Never```

NB: d3fk/kubectl has kubectl for entrypoint so only args are required.
